# Generated by Django 3.2.6 on 2022-11-30 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_product_price_from'),
        ('wedding_floral', '0002_rename_wedding_floral_wedding'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='wedding',
            new_name='wedding_floral',
        ),
        migrations.RenameModel(
            old_name='wedding_type',
            new_name='wedding_floral_type',
        ),
    ]
