# Generated by Django 3.2.6 on 2021-11-24 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0002_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='balloon_type',
            fields=[
                ('type_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.type')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
            bases=('shop.type',),
        ),
        migrations.CreateModel(
            name='balloon',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('order', models.PositiveIntegerField(default=0)),
                ('supplyment_image10', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('supplyment_image11', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('supplyment_image12', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('supplyment_image13', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('supplyment_image14', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('supplyment_image15', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('supplyment_image16', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('supplyment_image17', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('supplyment_image18', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('supplyment_image19', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='balloon.balloon_type')),
            ],
            options={
                'ordering': ['order'],
            },
            bases=('shop.product',),
        ),
    ]
