# Generated by Django 3.2.6 on 2021-11-06 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='balloon_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='balloon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('supplyment_image1', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('supplyment_image2', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('supplyment_image3', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('supplyment_image4', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('supplyment_image5', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('supplyment_image6', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('supplyment_image7', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('supplyment_image8', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('supplyment_image9', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='balloon.balloon_type')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
