# Generated by Django 3.2.6 on 2021-11-19 23:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balloon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balloon',
            name='description',
        ),
        migrations.RemoveField(
            model_name='balloon',
            name='name',
        ),
        migrations.RemoveField(
            model_name='balloon_type',
            name='type',
        ),
        migrations.AddField(
            model_name='balloon',
            name='description_cn',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balloon',
            name='description_en',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balloon',
            name='details_cn',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='balloon',
            name='details_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='balloon',
            name='name_cn',
            field=models.CharField(default='description', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balloon',
            name='name_en',
            field=models.CharField(default='description', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balloon',
            name='supplyment_image10',
            field=models.ImageField(default='image', upload_to='static/img/flowers/'),
        ),
        migrations.AddField(
            model_name='balloon',
            name='supplyment_image11',
            field=models.ImageField(default='image', upload_to='static/img/flowers/'),
        ),
        migrations.AddField(
            model_name='balloon',
            name='supplyment_image12',
            field=models.ImageField(default='image', upload_to='static/img/flowers/'),
        ),
        migrations.AddField(
            model_name='balloon',
            name='supplyment_image13',
            field=models.ImageField(default='image', upload_to='static/img/flowers/'),
        ),
        migrations.AddField(
            model_name='balloon',
            name='supplyment_image14',
            field=models.ImageField(default='image', upload_to='static/img/flowers/'),
        ),
        migrations.AddField(
            model_name='balloon',
            name='supplyment_image15',
            field=models.ImageField(default='image', upload_to='static/img/flowers/'),
        ),
        migrations.AddField(
            model_name='balloon',
            name='supplyment_image16',
            field=models.ImageField(default='image', upload_to='static/img/flowers/'),
        ),
        migrations.AddField(
            model_name='balloon',
            name='supplyment_image17',
            field=models.ImageField(default='image', upload_to='static/img/flowers/'),
        ),
        migrations.AddField(
            model_name='balloon',
            name='supplyment_image18',
            field=models.ImageField(default='image', upload_to='static/img/flowers/'),
        ),
        migrations.AddField(
            model_name='balloon',
            name='supplyment_image19',
            field=models.ImageField(default='image', upload_to='static/img/flowers/'),
        ),
        migrations.AddField(
            model_name='balloon_type',
            name='name_cn',
            field=models.CharField(default='description', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balloon_type',
            name='name_en',
            field=models.CharField(default='description', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
