# Generated by Django 3.2.6 on 2021-11-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0003_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='time',
            field=models.DateTimeField(default=None),
        ),
    ]
