# Generated by Django 3.2.6 on 2021-11-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0004_auto_20211104_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
