# Generated by Django 3.2.6 on 2021-11-04 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0006_alter_enquiry_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='time',
        ),
    ]
