# Generated by Django 3.2.6 on 2021-11-04 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0007_remove_enquiry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 4, 18, 48, 40, 64272)),
        ),
    ]
