# Generated by Django 3.2.6 on 2021-11-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0028_alter_enquiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
