# Generated by Django 3.2.6 on 2021-12-11 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20211208_1619'),
        ('party_decoration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party_decoration',
            name='main_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='party_decoration.balloon_type'),
        ),
        migrations.CreateModel(
            name='balloon_sub_type',
            fields=[
                ('type_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.type')),
                ('order', models.PositiveIntegerField(default=0)),
                ('main_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party_decoration.balloon_type')),
            ],
            options={
                'ordering': ['order'],
            },
            bases=('shop.type',),
        ),
        migrations.AlterField(
            model_name='party_decoration',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='party_decoration.balloon_sub_type'),
        ),
    ]
