# Generated by Django 3.2.6 on 2022-11-22 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party_decoration', '0002_auto_20211211_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party_decoration',
            name='type',
        ),
    ]
