# Generated by Django 3.2.6 on 2022-11-22 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party_decoration', '0003_remove_balloon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='party_decoration',
            name='sub_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='party_decoration.balloon_sub_type'),
        ),
    ]
