# Generated by Django 3.2.6 on 2022-11-30 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_product_price_from'),
        ('party_decoration', '0004_balloon_sub_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='party_decoration',
            new_name='balloon',
        ),
    ]
