# Generated by Django 3.2.6 on 2021-11-24 05:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('name_cn', models.CharField(max_length=50, null=True)),
                ('price', models.FloatField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_cn', models.TextField(null=True)),
                ('thumbnail', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('supplyment_image1', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('supplyment_image2', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('supplyment_image3', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('supplyment_image4', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('supplyment_image5', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('supplyment_image6', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('supplyment_image7', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('supplyment_image8', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('supplyment_image9', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('details_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('details_cn', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=50, unique=True)),
                ('name_cn', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
