# Generated by Django 3.2.6 on 2021-11-24 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shopping_Cart',
            new_name='ShoppingCart',
        ),
        migrations.CreateModel(
            name='ShoppingCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
                ('shopping_cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shoppingcart')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
                ('shopping_cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shoppingcart')),
            ],
        ),
    ]
