# Generated by Django 3.2.6 on 2021-11-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pickupordelivery',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('Pick Up', 'Pick Up'), ('Delivery', 'Delivery')], default=True, max_length=200),
        ),
    ]
