# Generated by Django 3.2.6 on 2021-12-08 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20211124_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='shopping_cart',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
        migrations.DeleteModel(
            name='ShoppingCartItem',
        ),
    ]
