# Generated by Django 3.2.6 on 2021-12-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20211208_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_cn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
