# Generated by Django 3.2.6 on 2021-12-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20211213_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_prefix',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
