# Generated by Django 3.2.6 on 2021-12-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_price_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_prefix',
        ),
        migrations.AddField(
            model_name='product',
            name='price_from',
            field=models.BooleanField(default=False),
        ),
    ]
