# Generated by Django 3.2.6 on 2022-11-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20211213_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_from',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
