# Generated by Django 3.2.6 on 2021-11-19 22:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='details_cn',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flower',
            name='details_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
