# Generated by Django 3.2.6 on 2021-12-08 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_auto_20211208_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flower_sub_type',
            old_name='type',
            new_name='main_type',
        ),
    ]
