# Generated by Django 3.2.6 on 2021-11-24 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0002_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='party_hire_type',
            fields=[
                ('type_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.type')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
            bases=('shop.type',),
        ),
        migrations.CreateModel(
            name='party_hire',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('order', models.PositiveIntegerField(default=0)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='party_hire.party_hire_type')),
            ],
            options={
                'ordering': ['order'],
            },
            bases=('shop.product',),
        ),
    ]
