# Generated by Django 3.2.6 on 2021-11-19 23:06

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party_hire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='party_hire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=50)),
                ('name_cn', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('description_en', models.TextField()),
                ('description_cn', models.TextField()),
                ('thumbnail', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('supplyment_image1', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('supplyment_image2', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('supplyment_image3', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('supplyment_image4', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('supplyment_image5', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('supplyment_image6', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('supplyment_image7', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('supplyment_image8', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('supplyment_image9', models.ImageField(default='image', upload_to='static/img/flowers/')),
                ('details_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('details_cn', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='party_hire_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=50, unique=True)),
                ('name_cn', models.CharField(max_length=50, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='partyhire',
        ),
        migrations.DeleteModel(
            name='partyhire_type',
        ),
        migrations.AddField(
            model_name='party_hire',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='party_hire.party_hire_type'),
        ),
    ]
