# Generated by Django 3.2.6 on 2021-12-12 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party_hire', '0002_auto_20211212_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='party_hire',
            name='main_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='party_hire.party_hire_type'),
            preserve_default=False,
        ),
    ]
